# Generated by Django 4.1.7 on 2023-03-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0002_accountv0'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountV0',
            new_name='AccountVO',
        ),
    ]
