# Generated by Django 4.1.7 on 2023-03-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0004_alter_accountvo_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvo',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
